/* data-flavor.js - procedural flavor-event pool + name pools (generated). */
(function (root) {
  "use strict";
  var App = root.App || (root.App = {});
  App.data = App.data || {};
  App.data.flavor = {
 "templates": [
  {
   "id": "stone-cultural-firstpaint",
   "type": "CULTURAL",
   "eraStart": -40000,
   "eraEnd": -3500,
   "anchor": "anyLand",
   "weight": 6,
   "name": "Ochre Hands at {place}",
   "desc": "Hunters of {civ} press red palms to the cave wall, marking that they were here."
  },
  {
   "id": "stone-cultural-omenfire",
   "type": "CULTURAL",
   "eraStart": -40000,
   "eraEnd": -3500,
   "anchor": "activeCiv",
   "weight": 5,
   "name": "The {omen} Honored",
   "desc": "{leader} leads {civ} in song around the great fire to honor {omen}."
  },
  {
   "id": "stone-cultural-bonecarve",
   "type": "CULTURAL",
   "eraStart": -40000,
   "eraEnd": -3500,
   "anchor": "anyLand",
   "weight": 4,
   "name": "Bone Flute at {place}",
   "desc": "A child of {civ} carves a flute from an eagle's wing and the camp learns a new song."
  },
  {
   "id": "stone-discovery-firekeep",
   "type": "DISCOVERY",
   "eraStart": -40000,
   "eraEnd": -3500,
   "anchor": "activeCiv",
   "weight": 6,
   "name": "Fire Tamed at {place}",
   "desc": "{civ} learns to bank the embers, and night loses some of its terror."
  },
  {
   "id": "stone-discovery-needle",
   "type": "DISCOVERY",
   "eraStart": -40000,
   "eraEnd": -3500,
   "anchor": "activeCiv",
   "weight": 5,
   "name": "The Bone Needle",
   "desc": "{leader} of {civ} threads sinew through bone, and the cold winters grow kinder."
  },
  {
   "id": "stone-discovery-dogfriend",
   "type": "DISCOVERY",
   "eraStart": -40000,
   "eraEnd": -3500,
   "anchor": "anyLand",
   "weight": 4,
   "name": "Wolf at the Fire",
   "desc": "Near {place} a wolf pup follows {civ} home, and a long friendship begins."
  },
  {
   "id": "stone-founding-camp",
   "type": "FOUNDING",
   "eraStart": -40000,
   "eraEnd": -3500,
   "anchor": "anyLand",
   "weight": 6,
   "name": "New Camp at {place}",
   "desc": "Following the herds, {civ} raises hide tents at {place}."
  },
  {
   "id": "stone-founding-shelter",
   "type": "FOUNDING",
   "eraStart": -40000,
   "eraEnd": -3500,
   "anchor": "anyLand",
   "weight": 4,
   "name": "Rock Shelter Found",
   "desc": "Scouts of {civ} claim a dry overhang at {place} before the rains."
  },
  {
   "id": "stone-war-huntdispute",
   "type": "WAR",
   "eraStart": -40000,
   "eraEnd": -3500,
   "anchor": "anyLand",
   "weight": 4,
   "name": "Clash over the Herd",
   "desc": "Two bands of {civ} quarrel over a fallen mammoth near {place}; spears are raised."
  },
  {
   "id": "stone-war-territory",
   "type": "WAR",
   "eraStart": -40000,
   "eraEnd": -3500,
   "anchor": "activeCiv",
   "weight": 3,
   "name": "The Valley Dispute",
   "desc": "{leader} drives a rival band from the hunting grounds of {civ}."
  },
  {
   "id": "stone-disaster-icewinter",
   "type": "DISASTER",
   "eraStart": -40000,
   "eraEnd": -3500,
   "anchor": "activeCiv",
   "weight": 5,
   "name": "The Long Winter",
   "desc": "Snow buries the camps of {civ} and the elders ration the last dried meat."
  },
  {
   "id": "stone-disaster-floodriver",
   "type": "DISASTER",
   "eraStart": -40000,
   "eraEnd": -3500,
   "anchor": "anyLand",
   "weight": 4,
   "name": "The River Rose",
   "desc": "Spring melt swallows the camp at {place}; {civ} flees to high ground."
  },
  {
   "id": "stone-collapse-bandsplit",
   "type": "COLLAPSE",
   "eraStart": -40000,
   "eraEnd": -3500,
   "anchor": "activeCiv",
   "weight": 3,
   "name": "The Band Scatters",
   "desc": "Hunger splits the people of {civ}; families wander off toward {place}."
  },
  {
   "id": "stone-trade-flintswap",
   "type": "TRADE",
   "eraStart": -40000,
   "eraEnd": -3500,
   "anchor": "anyLand",
   "weight": 5,
   "name": "Flint for Shells",
   "desc": "Strangers meet {civ} at {place} and trade fine flint for sea shells."
  },
  {
   "id": "stone-trade-amber",
   "type": "TRADE",
   "eraStart": -40000,
   "eraEnd": -3500,
   "anchor": "anyLand",
   "weight": 3,
   "name": "Amber from Afar",
   "desc": "A traveler brings glowing amber to {place}, and {civ} marvels at the trapped sun."
  },
  {
   "id": "stone-scientific-tally",
   "type": "SCIENTIFIC",
   "eraStart": -40000,
   "eraEnd": -3500,
   "anchor": "activeCiv",
   "weight": 3,
   "name": "Notches on Bone",
   "desc": "A shaman of {civ} scratches the moons onto a bone, counting the seasons."
  },
  {
   "id": "bronze-founding-temple",
   "type": "FOUNDING",
   "eraStart": -3200,
   "eraEnd": -1201,
   "anchor": "activeCiv",
   "weight": 6,
   "name": "Temple Raised at {place}",
   "desc": "{leader} of {civ} dedicates a mud-brick temple to {omen}."
  },
  {
   "id": "bronze-founding-citywall",
   "type": "FOUNDING",
   "eraStart": -3200,
   "eraEnd": -1201,
   "anchor": "anyLand",
   "weight": 5,
   "name": "Walls Rise at {place}",
   "desc": "{civ} encircles {place} with the first city walls."
  },
  {
   "id": "bronze-discovery-bronze",
   "type": "DISCOVERY",
   "eraStart": -3200,
   "eraEnd": -1201,
   "anchor": "activeCiv",
   "weight": 6,
   "name": "Tin Meets Copper",
   "desc": "Smiths of {civ} blend metals and pour the first bronze blade."
  },
  {
   "id": "bronze-discovery-wheel",
   "type": "DISCOVERY",
   "eraStart": -3200,
   "eraEnd": -1201,
   "anchor": "activeCiv",
   "weight": 5,
   "name": "The Turning Wheel",
   "desc": "A potter of {civ} fits an axle to a disk, and the cart is born."
  },
  {
   "id": "bronze-scientific-writing",
   "type": "SCIENTIFIC",
   "eraStart": -3200,
   "eraEnd": -1201,
   "anchor": "activeCiv",
   "weight": 5,
   "name": "Marks on Clay",
   "desc": "Scribes of {civ} press reeds into clay to count the harvest of {place}."
  },
  {
   "id": "bronze-scientific-calendar",
   "type": "SCIENTIFIC",
   "eraStart": -3200,
   "eraEnd": -1201,
   "anchor": "activeCiv",
   "weight": 4,
   "name": "The Star Calendar",
   "desc": "Priests of {civ} read {omen} in the sky and fix the year's first day."
  },
  {
   "id": "bronze-cultural-festival",
   "type": "CULTURAL",
   "eraStart": -3200,
   "eraEnd": -1201,
   "anchor": "activeCiv",
   "weight": 6,
   "name": "The {festival} at {place}",
   "desc": "{civ} fills the streets of {place} for the {festival}, honoring {omen}."
  },
  {
   "id": "bronze-cultural-ziggurat",
   "type": "CULTURAL",
   "eraStart": -3200,
   "eraEnd": -1201,
   "anchor": "activeCiv",
   "weight": 4,
   "name": "Songs for {leader}",
   "desc": "Court poets of {civ} compose hymns praising {leader} and the gods."
  },
  {
   "id": "bronze-trade-caravan",
   "type": "TRADE",
   "eraStart": -3200,
   "eraEnd": -1201,
   "anchor": "anyLand",
   "weight": 6,
   "name": "Caravan to {place}",
   "desc": "Donkey trains of {civ} carry grain and lapis toward {place}."
  },
  {
   "id": "bronze-trade-river",
   "type": "TRADE",
   "eraStart": -3200,
   "eraEnd": -1201,
   "anchor": "anyLand",
   "weight": 4,
   "name": "River Barges Laden",
   "desc": "Reed boats of {civ} drift down to {place} heavy with copper and cloth."
  },
  {
   "id": "bronze-war-citystate",
   "type": "WAR",
   "eraStart": -3200,
   "eraEnd": -1201,
   "anchor": "activeCiv",
   "weight": 5,
   "name": "{leader} Marches on {place}",
   "desc": "{leader} of {civ} besieges rival {place} over a stolen idol."
  },
  {
   "id": "bronze-war-chariot",
   "type": "WAR",
   "eraStart": -3200,
   "eraEnd": -1201,
   "anchor": "activeCiv",
   "weight": 4,
   "name": "Chariots at Dawn",
   "desc": "The chariots of {civ} thunder across the plain to break a raiding host."
  },
  {
   "id": "bronze-disaster-drought",
   "type": "DISASTER",
   "eraStart": -3200,
   "eraEnd": -1201,
   "anchor": "activeCiv",
   "weight": 5,
   "name": "The River Failed",
   "desc": "The flood does not come, and the granaries of {civ} run thin."
  },
  {
   "id": "bronze-disaster-locust",
   "type": "DISASTER",
   "eraStart": -3200,
   "eraEnd": -1201,
   "anchor": "anyLand",
   "weight": 4,
   "name": "Locusts over {place}",
   "desc": "A black cloud strips the fields of {place}; {civ} calls it the wrath of {omen}."
  },
  {
   "id": "bronze-collapse-citydust",
   "type": "COLLAPSE",
   "eraStart": -3200,
   "eraEnd": -1201,
   "anchor": "anyLand",
   "weight": 3,
   "name": "{place} Abandoned",
   "desc": "Salt poisons the soil and {civ} leaves {place} to the wind."
  },
  {
   "id": "iron-discovery-iron",
   "type": "DISCOVERY",
   "eraStart": -1200,
   "eraEnd": -501,
   "anchor": "activeCiv",
   "weight": 6,
   "name": "The Black Metal",
   "desc": "Smiths of {civ} master the forge and beat iron into keen edges."
  },
  {
   "id": "iron-discovery-alphabet",
   "type": "DISCOVERY",
   "eraStart": -1200,
   "eraEnd": -501,
   "anchor": "activeCiv",
   "weight": 4,
   "name": "Letters for All",
   "desc": "Traders of {civ} spread a simple alphabet through the ports."
  },
  {
   "id": "iron-scientific-coin",
   "type": "SCIENTIFIC",
   "eraStart": -1200,
   "eraEnd": -501,
   "anchor": "activeCiv",
   "weight": 4,
   "name": "The First Coins",
   "desc": "{civ} stamps {leader}'s mark on electrum, and money is born."
  },
  {
   "id": "iron-founding-colony",
   "type": "FOUNDING",
   "eraStart": -1200,
   "eraEnd": -501,
   "anchor": "anyLand",
   "weight": 6,
   "name": "Colony at {place}",
   "desc": "Settlers of {civ} found a trading colony on the shore of {place}."
  },
  {
   "id": "iron-cultural-oracle",
   "type": "CULTURAL",
   "eraStart": -1200,
   "eraEnd": -501,
   "anchor": "activeCiv",
   "weight": 5,
   "name": "The Oracle Speaks",
   "desc": "Pilgrims of {civ} climb to {place} to hear {omen} foretold."
  },
  {
   "id": "iron-cultural-games",
   "type": "CULTURAL",
   "eraStart": -1200,
   "eraEnd": -501,
   "anchor": "activeCiv",
   "weight": 5,
   "name": "{festival} Games at {place}",
   "desc": "Athletes of {civ} gather at {place} for the {festival}."
  },
  {
   "id": "iron-war-raiders",
   "type": "WAR",
   "eraStart": -1200,
   "eraEnd": -501,
   "anchor": "anyLand",
   "weight": 6,
   "name": "Sea Raiders at {place}",
   "desc": "Strange ships fall upon {place}; the men of {civ} muster to the shore."
  },
  {
   "id": "iron-war-king",
   "type": "WAR",
   "eraStart": -1200,
   "eraEnd": -501,
   "anchor": "activeCiv",
   "weight": 5,
   "name": "{leader} Conquers {place}",
   "desc": "{leader} of {civ} adds {place} to a growing kingdom by the sword."
  },
  {
   "id": "iron-trade-caravan",
   "type": "TRADE",
   "eraStart": -1200,
   "eraEnd": -501,
   "anchor": "anyLand",
   "weight": 5,
   "name": "Spice Road to {place}",
   "desc": "Merchants of {civ} open a new road carrying spice and dye to {place}."
  },
  {
   "id": "iron-disaster-plague",
   "type": "DISASTER",
   "eraStart": -1200,
   "eraEnd": -501,
   "anchor": "activeCiv",
   "weight": 4,
   "name": "Fever in the Camp",
   "desc": "A wasting fever spreads through {civ}; the healers burn herbs against {omen}."
  },
  {
   "id": "iron-collapse-dynasty",
   "type": "COLLAPSE",
   "eraStart": -1200,
   "eraEnd": -501,
   "anchor": "activeCiv",
   "weight": 3,
   "name": "The House Falls",
   "desc": "Rivals murder {leader} and the kingdom of {civ} splinters."
  },
  {
   "id": "iron-scientific-irrigate",
   "type": "SCIENTIFIC",
   "eraStart": -1200,
   "eraEnd": -501,
   "anchor": "anyLand",
   "weight": 3,
   "name": "Canals at {place}",
   "desc": "Engineers of {civ} cut canals to green the fields of {place}."
  },
  {
   "id": "class-cultural-philosophy",
   "type": "CULTURAL",
   "eraStart": -500,
   "eraEnd": 499,
   "anchor": "activeCiv",
   "weight": 6,
   "name": "Sages Debate at {place}",
   "desc": "Philosophers of {civ} argue the nature of {omen} in the agora of {place}."
  },
  {
   "id": "class-cultural-theater",
   "type": "CULTURAL",
   "eraStart": -500,
   "eraEnd": 499,
   "anchor": "activeCiv",
   "weight": 5,
   "name": "{festival} at {place}",
   "desc": "Crowds of {civ} pack the theater of {place} for the {festival}."
  },
  {
   "id": "class-scientific-geometry",
   "type": "SCIENTIFIC",
   "eraStart": -500,
   "eraEnd": 499,
   "anchor": "activeCiv",
   "weight": 5,
   "name": "Proof in the Sand",
   "desc": "A geometer of {civ} draws a proof and the students of {place} gasp."
  },
  {
   "id": "class-scientific-aqueduct",
   "type": "SCIENTIFIC",
   "eraStart": -500,
   "eraEnd": 499,
   "anchor": "anyLand",
   "weight": 4,
   "name": "Aqueduct to {place}",
   "desc": "{civ} carries fresh water to {place} on stone arches."
  },
  {
   "id": "class-founding-newcity",
   "type": "FOUNDING",
   "eraStart": -500,
   "eraEnd": 499,
   "anchor": "anyLand",
   "weight": 5,
   "name": "{leader} Founds {place}",
   "desc": "{leader} of {civ} lays out a grand new city at {place}."
  },
  {
   "id": "class-war-legion",
   "type": "WAR",
   "eraStart": -500,
   "eraEnd": 499,
   "anchor": "activeCiv",
   "weight": 6,
   "name": "Legions to {place}",
   "desc": "The disciplined ranks of {civ} march on {place} under {leader}."
  },
  {
   "id": "class-war-revolt",
   "type": "WAR",
   "eraStart": -500,
   "eraEnd": 499,
   "anchor": "anyLand",
   "weight": 4,
   "name": "Revolt at {place}",
   "desc": "Taxed too hard, the people of {place} rise against {civ}."
  },
  {
   "id": "class-trade-silk",
   "type": "TRADE",
   "eraStart": -500,
   "eraEnd": 499,
   "anchor": "anyLand",
   "weight": 5,
   "name": "Silk Reaches {place}",
   "desc": "A caravan of {civ} brings eastern silk to the markets of {place}."
  },
  {
   "id": "class-discovery-paper",
   "type": "DISCOVERY",
   "eraStart": -500,
   "eraEnd": 499,
   "anchor": "activeCiv",
   "weight": 4,
   "name": "Pulp into Paper",
   "desc": "An inventor of {civ} mats fibers into a fine sheet for writing."
  },
  {
   "id": "class-disaster-eruption",
   "type": "DISASTER",
   "eraStart": -500,
   "eraEnd": 499,
   "anchor": "anyLand",
   "weight": 3,
   "name": "Ash over {place}",
   "desc": "A mountain burns and ash rains on {place}; {civ} fears the anger of {omen}."
  },
  {
   "id": "class-collapse-frontier",
   "type": "COLLAPSE",
   "eraStart": -500,
   "eraEnd": 499,
   "anchor": "activeCiv",
   "weight": 3,
   "name": "The Frontier Breaks",
   "desc": "Barbarian bands pour past the worn defenses of {civ}."
  },
  {
   "id": "dark-founding-monastery",
   "type": "FOUNDING",
   "eraStart": 500,
   "eraEnd": 999,
   "anchor": "anyLand",
   "weight": 6,
   "name": "Monastery at {place}",
   "desc": "Monks of {civ} raise a quiet monastery at {place} to keep the old books."
  },
  {
   "id": "dark-cultural-saint",
   "type": "CULTURAL",
   "eraStart": 500,
   "eraEnd": 999,
   "anchor": "activeCiv",
   "weight": 5,
   "name": "Relics Come to {place}",
   "desc": "Pilgrims of {civ} flock to {place} where a saint's bones now rest."
  },
  {
   "id": "dark-war-raid",
   "type": "WAR",
   "eraStart": 500,
   "eraEnd": 999,
   "anchor": "anyLand",
   "weight": 6,
   "name": "Longships at {place}",
   "desc": "Raiders descend on {place}; the folk of {civ} flee inland with their gold."
  },
  {
   "id": "dark-war-warlord",
   "type": "WAR",
   "eraStart": 500,
   "eraEnd": 999,
   "anchor": "activeCiv",
   "weight": 5,
   "name": "{leader} Takes the Throne",
   "desc": "{leader} of {civ} seizes power by the blade and the loyalty of warriors."
  },
  {
   "id": "dark-discovery-stirrup",
   "type": "DISCOVERY",
   "eraStart": 500,
   "eraEnd": 999,
   "anchor": "activeCiv",
   "weight": 4,
   "name": "Feet in Iron",
   "desc": "Riders of {civ} adopt the stirrup and the heavy cavalry is born."
  },
  {
   "id": "dark-scientific-astrolabe",
   "type": "SCIENTIFIC",
   "eraStart": 500,
   "eraEnd": 999,
   "anchor": "activeCiv",
   "weight": 4,
   "name": "Stars by Brass",
   "desc": "Scholars of {civ} perfect the astrolabe to read {omen} and find the way."
  },
  {
   "id": "dark-trade-fair",
   "type": "TRADE",
   "eraStart": 500,
   "eraEnd": 999,
   "anchor": "anyLand",
   "weight": 5,
   "name": "Great Fair at {place}",
   "desc": "Merchants of {civ} crowd {place} for the season's great trading fair."
  },
  {
   "id": "dark-trade-gold",
   "type": "TRADE",
   "eraStart": 500,
   "eraEnd": 999,
   "anchor": "anyLand",
   "weight": 4,
   "name": "Gold and Salt at {place}",
   "desc": "Camel trains of {civ} exchange salt for gold across the sands near {place}."
  },
  {
   "id": "dark-disaster-plague",
   "type": "DISASTER",
   "eraStart": 500,
   "eraEnd": 999,
   "anchor": "activeCiv",
   "weight": 4,
   "name": "The Black Fever",
   "desc": "Plague stalks {civ}; carts of the dead roll out of {place} each dawn."
  },
  {
   "id": "dark-collapse-sack",
   "type": "COLLAPSE",
   "eraStart": 500,
   "eraEnd": 999,
   "anchor": "anyLand",
   "weight": 3,
   "name": "{place} Sacked",
   "desc": "Invaders burn {place} and the rule of {civ} there ends in smoke."
  },
  {
   "id": "dark-cultural-epic",
   "type": "CULTURAL",
   "eraStart": 500,
   "eraEnd": 999,
   "anchor": "activeCiv",
   "weight": 3,
   "name": "The Bard's Saga",
   "desc": "A bard of {civ} sings a new epic of {leader} in the mead hall."
  },
  {
   "id": "med-founding-cathedral",
   "type": "FOUNDING",
   "eraStart": 1000,
   "eraEnd": 1399,
   "anchor": "anyLand",
   "weight": 6,
   "name": "Cathedral at {place}",
   "desc": "Masons of {civ} begin a soaring cathedral at {place} that will take a lifetime."
  },
  {
   "id": "med-founding-university",
   "type": "FOUNDING",
   "eraStart": 1000,
   "eraEnd": 1399,
   "anchor": "anyLand",
   "weight": 4,
   "name": "Scholars Gather at {place}",
   "desc": "A university opens at {place} as scholars of {civ} flock to study."
  },
  {
   "id": "med-cultural-tourney",
   "type": "CULTURAL",
   "eraStart": 1000,
   "eraEnd": 1399,
   "anchor": "activeCiv",
   "weight": 5,
   "name": "{festival} Tourney at {place}",
   "desc": "Knights of {civ} joust at {place} for the honor of {leader}."
  },
  {
   "id": "med-war-crusade",
   "type": "WAR",
   "eraStart": 1000,
   "eraEnd": 1399,
   "anchor": "activeCiv",
   "weight": 5,
   "name": "{leader} Calls the Host",
   "desc": "{leader} of {civ} summons a holy army to march on {place}."
  },
  {
   "id": "med-war-siege",
   "type": "WAR",
   "eraStart": 1000,
   "eraEnd": 1399,
   "anchor": "anyLand",
   "weight": 6,
   "name": "Siege of {place}",
   "desc": "Trebuchets of {civ} pound the walls of {place} through a long winter."
  },
  {
   "id": "med-discovery-compass",
   "type": "DISCOVERY",
   "eraStart": 1000,
   "eraEnd": 1399,
   "anchor": "activeCiv",
   "weight": 4,
   "name": "The Needle Points North",
   "desc": "Sailors of {civ} steer by a floating needle even when no stars show."
  },
  {
   "id": "med-discovery-gunpowder",
   "type": "DISCOVERY",
   "eraStart": 1000,
   "eraEnd": 1399,
   "anchor": "activeCiv",
   "weight": 4,
   "name": "Thunder Powder",
   "desc": "Alchemists of {civ} pack a black powder that roars and spits fire."
  },
  {
   "id": "med-trade-spice",
   "type": "TRADE",
   "eraStart": 1000,
   "eraEnd": 1399,
   "anchor": "anyLand",
   "weight": 6,
   "name": "Spice Fleet to {place}",
   "desc": "Galleys of {civ} return to {place} laden with pepper and silk."
  },
  {
   "id": "med-scientific-clock",
   "type": "SCIENTIFIC",
   "eraStart": 1000,
   "eraEnd": 1399,
   "anchor": "anyLand",
   "weight": 3,
   "name": "The Striking Clock",
   "desc": "A mechanical clock chimes the hours over the square of {place}."
  },
  {
   "id": "med-disaster-plague",
   "type": "DISASTER",
   "eraStart": 1000,
   "eraEnd": 1399,
   "anchor": "activeCiv",
   "weight": 5,
   "name": "The Great Mortality",
   "desc": "A pestilence empties the towns of {civ}; one in three is gone by spring."
  },
  {
   "id": "med-collapse-peasants",
   "type": "COLLAPSE",
   "eraStart": 1000,
   "eraEnd": 1399,
   "anchor": "anyLand",
   "weight": 3,
   "name": "Revolt at {place}",
   "desc": "Hungry peasants of {civ} march on {place} with scythes and torches."
  },
  {
   "id": "ren-discovery-press",
   "type": "DISCOVERY",
   "eraStart": 1400,
   "eraEnd": 1699,
   "anchor": "activeCiv",
   "weight": 6,
   "name": "Books by the Press",
   "desc": "Printers of {civ} run off books faster than scribes ever could."
  },
  {
   "id": "ren-discovery-newland",
   "type": "DISCOVERY",
   "eraStart": 1400,
   "eraEnd": 1699,
   "anchor": "anyLand",
   "weight": 5,
   "name": "Sails toward {place}",
   "desc": "Explorers of {civ} chart a bold course past {place} into open sea."
  },
  {
   "id": "ren-cultural-masters",
   "type": "CULTURAL",
   "eraStart": 1400,
   "eraEnd": 1699,
   "anchor": "activeCiv",
   "weight": 6,
   "name": "Master Painter at {place}",
   "desc": "A painter of {civ} unveils a marvel that draws crowds to {place}."
  },
  {
   "id": "ren-cultural-festival",
   "type": "CULTURAL",
   "eraStart": 1400,
   "eraEnd": 1699,
   "anchor": "activeCiv",
   "weight": 4,
   "name": "{festival} at {place}",
   "desc": "Masked revelers of {civ} fill {place} for the {festival}."
  },
  {
   "id": "ren-scientific-telescope",
   "type": "SCIENTIFIC",
   "eraStart": 1400,
   "eraEnd": 1699,
   "anchor": "activeCiv",
   "weight": 5,
   "name": "Glass to the Heavens",
   "desc": "A scholar of {civ} turns a long glass skyward and counts new moons by {omen}."
  },
  {
   "id": "ren-founding-tradehouse",
   "type": "FOUNDING",
   "eraStart": 1400,
   "eraEnd": 1699,
   "anchor": "anyLand",
   "weight": 5,
   "name": "Trading House at {place}",
   "desc": "Merchants of {civ} open a fortified trading house at {place}."
  },
  {
   "id": "ren-war-mercenary",
   "type": "WAR",
   "eraStart": 1400,
   "eraEnd": 1699,
   "anchor": "activeCiv",
   "weight": 5,
   "name": "{leader} Hires the Pikes",
   "desc": "{leader} of {civ} marches with mercenary pikes and cannon on {place}."
  },
  {
   "id": "ren-war-armada",
   "type": "WAR",
   "eraStart": 1400,
   "eraEnd": 1699,
   "anchor": "anyLand",
   "weight": 4,
   "name": "Fleets Clash off {place}",
   "desc": "Gun decks of {civ} trade broadsides with a rival fleet near {place}."
  },
  {
   "id": "ren-trade-galleon",
   "type": "TRADE",
   "eraStart": 1400,
   "eraEnd": 1699,
   "anchor": "anyLand",
   "weight": 6,
   "name": "Silver Galleon at {place}",
   "desc": "A treasure galleon of {civ} docks at {place} heavy with silver."
  },
  {
   "id": "ren-disaster-fire",
   "type": "DISASTER",
   "eraStart": 1400,
   "eraEnd": 1699,
   "anchor": "anyLand",
   "weight": 4,
   "name": "Great Fire at {place}",
   "desc": "Flames sweep the timbered streets of {place}; {civ} fights the blaze for days."
  },
  {
   "id": "ren-collapse-debt",
   "type": "COLLAPSE",
   "eraStart": 1400,
   "eraEnd": 1699,
   "anchor": "activeCiv",
   "weight": 3,
   "name": "The Crown Bankrupt",
   "desc": "War debts ruin the treasury of {civ}, and the bankers of {place} despair."
  },
  {
   "id": "ind-discovery-steam",
   "type": "DISCOVERY",
   "eraStart": 1700,
   "eraEnd": 1899,
   "anchor": "activeCiv",
   "weight": 6,
   "name": "Steam Turns the Wheel",
   "desc": "Engineers of {civ} harness steam, and the mills of {place} never sleep."
  },
  {
   "id": "ind-discovery-rail",
   "type": "DISCOVERY",
   "eraStart": 1700,
   "eraEnd": 1899,
   "anchor": "anyLand",
   "weight": 5,
   "name": "Iron Rails to {place}",
   "desc": "A railway of {civ} reaches {place}, and the journey of weeks becomes a day."
  },
  {
   "id": "ind-scientific-vaccine",
   "type": "SCIENTIFIC",
   "eraStart": 1700,
   "eraEnd": 1899,
   "anchor": "activeCiv",
   "weight": 5,
   "name": "The Healing Prick",
   "desc": "Doctors of {civ} inoculate the children of {place} against the pox."
  },
  {
   "id": "ind-scientific-telegraph",
   "type": "SCIENTIFIC",
   "eraStart": 1700,
   "eraEnd": 1899,
   "anchor": "anyLand",
   "weight": 4,
   "name": "Wires Reach {place}",
   "desc": "The telegraph clicks into {place}; word of {civ} now flies on copper."
  },
  {
   "id": "ind-founding-factory",
   "type": "FOUNDING",
   "eraStart": 1700,
   "eraEnd": 1899,
   "anchor": "anyLand",
   "weight": 5,
   "name": "Mill Town at {place}",
   "desc": "Chimneys of {civ} rise over {place} as a mill town springs up overnight."
  },
  {
   "id": "ind-cultural-worldsfair",
   "type": "CULTURAL",
   "eraStart": 1700,
   "eraEnd": 1899,
   "anchor": "activeCiv",
   "weight": 4,
   "name": "Grand Exhibition at {place}",
   "desc": "{civ} dazzles the world with an exhibition of machines at {place}."
  },
  {
   "id": "ind-war-rifles",
   "type": "WAR",
   "eraStart": 1700,
   "eraEnd": 1899,
   "anchor": "activeCiv",
   "weight": 5,
   "name": "{leader} Marches on {place}",
   "desc": "Rifled columns of {civ} under {leader} advance on {place} in the rain."
  },
  {
   "id": "ind-war-rebellion",
   "type": "WAR",
   "eraStart": 1700,
   "eraEnd": 1899,
   "anchor": "anyLand",
   "weight": 4,
   "name": "Uprising at {place}",
   "desc": "Citizens of {place} raise barricades against the rule of {civ}."
  },
  {
   "id": "ind-trade-cotton",
   "type": "TRADE",
   "eraStart": 1700,
   "eraEnd": 1899,
   "anchor": "anyLand",
   "weight": 5,
   "name": "Cotton Bales to {place}",
   "desc": "Clipper ships of {civ} crowd the docks of {place} with bales and tea."
  },
  {
   "id": "ind-disaster-cholera",
   "type": "DISASTER",
   "eraStart": 1700,
   "eraEnd": 1899,
   "anchor": "anyLand",
   "weight": 4,
   "name": "Cholera in {place}",
   "desc": "Foul water brings cholera to {place}; the slums of {civ} reel."
  },
  {
   "id": "ind-collapse-crash",
   "type": "COLLAPSE",
   "eraStart": 1700,
   "eraEnd": 1899,
   "anchor": "activeCiv",
   "weight": 3,
   "name": "The Panic",
   "desc": "Banks of {civ} fail and the markets of {place} crash overnight."
  },
  {
   "id": "mod-discovery-flight",
   "type": "DISCOVERY",
   "eraStart": 1900,
   "eraEnd": 1999,
   "anchor": "activeCiv",
   "weight": 6,
   "name": "Wings over {place}",
   "desc": "Aviators of {civ} take to the air above {place} for the first time."
  },
  {
   "id": "mod-discovery-radio",
   "type": "DISCOVERY",
   "eraStart": 1900,
   "eraEnd": 1999,
   "anchor": "anyLand",
   "weight": 5,
   "name": "Voices on the Air",
   "desc": "Radio crackles to life in {place} as {civ} broadcasts to the masses."
  },
  {
   "id": "mod-scientific-antibiotic",
   "type": "SCIENTIFIC",
   "eraStart": 1900,
   "eraEnd": 1999,
   "anchor": "activeCiv",
   "weight": 5,
   "name": "The Mold That Heals",
   "desc": "Researchers of {civ} brew a medicine that defeats deadly wounds."
  },
  {
   "id": "mod-scientific-atom",
   "type": "SCIENTIFIC",
   "eraStart": 1900,
   "eraEnd": 1999,
   "anchor": "activeCiv",
   "weight": 4,
   "name": "Splitting the Atom",
   "desc": "Physicists of {civ} unlock the power hidden inside matter itself."
  },
  {
   "id": "mod-cultural-cinema",
   "type": "CULTURAL",
   "eraStart": 1900,
   "eraEnd": 1999,
   "anchor": "activeCiv",
   "weight": 5,
   "name": "Picture Palace at {place}",
   "desc": "Crowds of {civ} line up at {place} for the new moving pictures."
  },
  {
   "id": "mod-cultural-olympiad",
   "type": "CULTURAL",
   "eraStart": 1900,
   "eraEnd": 1999,
   "anchor": "anyLand",
   "weight": 4,
   "name": "{festival} Games at {place}",
   "desc": "Athletes of {civ} gather at {place} for the {festival}."
  },
  {
   "id": "mod-founding-skyline",
   "type": "FOUNDING",
   "eraStart": 1900,
   "eraEnd": 1999,
   "anchor": "anyLand",
   "weight": 4,
   "name": "Towers Rise at {place}",
   "desc": "Steel skyscrapers of {civ} climb over {place} toward the clouds."
  },
  {
   "id": "mod-war-frontline",
   "type": "WAR",
   "eraStart": 1900,
   "eraEnd": 1999,
   "anchor": "anyLand",
   "weight": 5,
   "name": "Battle near {place}",
   "desc": "Armies of {civ} dig in around {place} as the front grinds forward."
  },
  {
   "id": "mod-trade-oil",
   "type": "TRADE",
   "eraStart": 1900,
   "eraEnd": 1999,
   "anchor": "anyLand",
   "weight": 5,
   "name": "Oil Strike at {place}",
   "desc": "Derricks of {civ} gush black gold near {place}, and fortunes shift."
  },
  {
   "id": "mod-disaster-quake",
   "type": "DISASTER",
   "eraStart": 1900,
   "eraEnd": 1999,
   "anchor": "anyLand",
   "weight": 4,
   "name": "Earthquake at {place}",
   "desc": "The ground heaves beneath {place}; {civ} digs through the rubble for days."
  },
  {
   "id": "mod-collapse-empire",
   "type": "COLLAPSE",
   "eraStart": 1900,
   "eraEnd": 1999,
   "anchor": "activeCiv",
   "weight": 3,
   "name": "The Old Order Falls",
   "desc": "Crowds in {place} topple the old rulers of {civ} as the empire dissolves."
  },
  {
   "id": "info-discovery-internet",
   "type": "DISCOVERY",
   "eraStart": 2000,
   "eraEnd": 2025,
   "anchor": "activeCiv",
   "weight": 6,
   "name": "The Network Spreads",
   "desc": "Citizens of {civ} log on as the web threads every home in {place}."
  },
  {
   "id": "info-scientific-genome",
   "type": "SCIENTIFIC",
   "eraStart": 2000,
   "eraEnd": 2025,
   "anchor": "activeCiv",
   "weight": 5,
   "name": "The Code of Life",
   "desc": "Scientists of {civ} map the human genome and rewrite medicine."
  },
  {
   "id": "info-scientific-ai",
   "type": "SCIENTIFIC",
   "eraStart": 2000,
   "eraEnd": 2025,
   "anchor": "activeCiv",
   "weight": 4,
   "name": "Machines That Learn",
   "desc": "Engineers of {civ} build thinking machines that answer in {place} and beyond."
  },
  {
   "id": "info-cultural-viral",
   "type": "CULTURAL",
   "eraStart": 2000,
   "eraEnd": 2025,
   "anchor": "activeCiv",
   "weight": 5,
   "name": "A Craze Sweeps {place}",
   "desc": "A craze leaps screen to screen across {civ}, born in {place} overnight."
  },
  {
   "id": "info-founding-startup",
   "type": "FOUNDING",
   "eraStart": 2000,
   "eraEnd": 2025,
   "anchor": "anyLand",
   "weight": 5,
   "name": "Startup Boom at {place}",
   "desc": "Young founders of {civ} flock to {place} chasing the next big thing."
  },
  {
   "id": "info-trade-container",
   "type": "TRADE",
   "eraStart": 2000,
   "eraEnd": 2025,
   "anchor": "anyLand",
   "weight": 5,
   "name": "Container Port at {place}",
   "desc": "Giant ships of {civ} stack containers high at the port of {place}."
  },
  {
   "id": "info-war-cyber",
   "type": "WAR",
   "eraStart": 2000,
   "eraEnd": 2025,
   "anchor": "activeCiv",
   "weight": 4,
   "name": "Networks under Siege",
   "desc": "Unseen attackers strike the systems of {civ}; {place} goes dark for hours."
  },
  {
   "id": "info-disaster-pandemic",
   "type": "DISASTER",
   "eraStart": 2000,
   "eraEnd": 2025,
   "anchor": "activeCiv",
   "weight": 4,
   "name": "The Great Lockdown",
   "desc": "A new plague closes the streets of {civ}; {place} falls silent for months."
  },
  {
   "id": "info-disaster-storm",
   "type": "DISASTER",
   "eraStart": 2000,
   "eraEnd": 2025,
   "anchor": "anyLand",
   "weight": 4,
   "name": "Superstorm at {place}",
   "desc": "A vast storm batters {place}; the people of {civ} brace and rebuild."
  },
  {
   "id": "info-collapse-meltdown",
   "type": "COLLAPSE",
   "eraStart": 2000,
   "eraEnd": 2025,
   "anchor": "activeCiv",
   "weight": 3,
   "name": "Markets in Freefall",
   "desc": "A financial shock ripples through {civ}; the exchanges of {place} crater."
  },
  {
   "id": "info-cultural-festival",
   "type": "CULTURAL",
   "eraStart": 2000,
   "eraEnd": 2025,
   "anchor": "anyLand",
   "weight": 4,
   "name": "{festival} Draws Millions to {place}",
   "desc": "Fans of {civ} stream into {place} for the {festival}."
  }
 ],
 "namePools": {
  "settlements": [
   "Ravenford",
   "Stonehollow",
   "Saltmarsh",
   "Greywater",
   "Oakhaven",
   "Ironvale",
   "Redcliff",
   "Highmoor",
   "Westgate",
   "Thornwick",
   "Coldspring",
   "Amberhall",
   "Brightwater",
   "Duskford",
   "Riverbend",
   "Goldmeadow",
   "Blackbarrow",
   "Windmere",
   "Fellgate",
   "Mistholt",
   "Stormhaven",
   "Greenford",
   "Ashford",
   "Larkhill",
   "Sunderland",
   "Marshend",
   "Crowstead",
   "Pinehurst",
   "Foxglade",
   "Hawkridge",
   "Elmwood",
   "Bramblewick",
   "Deepwell",
   "Frostmere",
   "Tideport",
   "Reedmarsh",
   "Whitebridge",
   "Copperdale",
   "Longshore",
   "Hartwell",
   "Briarcliff",
   "Nethergate",
   "Sandholm",
   "Birchvale",
   "Cragmoor",
   "Dewbury",
   "Fairhaven",
   "Glenmark",
   "Hollowmere",
   "Kestrelford",
   "Lowmarsh",
   "Mossgard",
   "Norwick",
   "Oldharbor",
   "Quillford",
   "Rookhaven",
   "Stagmoor",
   "Thistlewen",
   "Underhill",
   "Wolfden"
  ],
  "leaders": [
   "King Aldric",
   "Queen Maeve",
   "Chief Tarok",
   "Lady Ysolde",
   "Lord Bercan",
   "Sargon the Bold",
   "Nefari the Wise",
   "Khan Berke",
   "Empress Lian",
   "Raja Devan",
   "Pharaoh Khaem",
   "Tsar Vladar",
   "Sultan Yusuf",
   "Doge Marco",
   "Caliph Harun",
   "Elder Brynn",
   "Warlord Gorm",
   "Princess Aine",
   "Consul Tullius",
   "Shah Darius",
   "Mansa Keita",
   "Chieftain Una",
   "Duke Roderick",
   "Matriarch Sela",
   "Jarl Sigrun",
   "Emir Tariq",
   "Queen Boudica",
   "King Cormac",
   "Lady Isenda",
   "Lord Hawkeye",
   "Negus Tewolde",
   "Inca Yupanqui",
   "Tlatoani Cuauh",
   "Shogun Tadashi",
   "Khagan Ogai",
   "Basileus Leo",
   "Vizier Nizam",
   "Hetman Ostap",
   "Margrave Otto",
   "Count Aldo",
   "Queen Amina",
   "King Sundiata",
   "Elder Mara",
   "Chief Atohi",
   "Lady Genevra",
   "Warleader Volk",
   "Priest-King Eridu",
   "Regent Soraya",
   "Lord Caedwall",
   "Lady Thessaly",
   "Captain Halvar",
   "Governor Pellan",
   "Archon Kleon",
   "Despot Vuk",
   "Queen Tamar",
   "King Brennus",
   "Chief Mokosh",
   "Lady Orla",
   "Lord Wystan",
   "Elder Tovi"
  ],
  "omens": [
   "the Comet",
   "the Blood Moon",
   "the Twin Suns",
   "the Falling Star",
   "the Black Raven",
   "the Sky Serpent",
   "the White Stag",
   "the Eclipse",
   "the Storm Bird",
   "the River Spirit",
   "the Ancestors",
   "the Sun Father",
   "the Moon Mother",
   "the Thunder God",
   "the Sea Lord",
   "the Harvest Maiden",
   "the Wolf Spirit",
   "the Burning Sky",
   "the Silent Dawn",
   "the Red Aurora",
   "the Owl at Noon",
   "the Weeping Idol",
   "the Dancing Lights",
   "the Fire in the North",
   "the Green Flame",
   "the Howling Wind",
   "the Sacred Bull",
   "the Drowned King",
   "the Pale Horse",
   "the Singing Stones",
   "the Mountain's Wrath",
   "the Frozen Tide",
   "the Whispering Grove",
   "the Crimson Dusk",
   "the Star of Morning",
   "the Two-Tailed Comet",
   "the Lightning Tree",
   "the Black Sun",
   "the Golden Hare",
   "the Serpent's Egg"
  ],
  "festivals": [
   "Harvest Feast",
   "Midwinter Rite",
   "Festival of Lanterns",
   "Day of the Dead",
   "Spring Dance",
   "Sun Festival",
   "Moon Vigil",
   "Feast of Fools",
   "Rite of Renewal",
   "Founders' Day",
   "Festival of Masks",
   "Water Blessing",
   "Fire Procession",
   "Bull Run",
   "Flower Crowning",
   "Saints' Carnival",
   "Dragon Parade",
   "Lantern Voyage",
   "Reaping Games",
   "Solstice Gathering",
   "Festival of Kites",
   "Bread and Salt",
   "Ancestor Rites",
   "Star Festival",
   "Victory Games",
   "Pilgrim's Fair",
   "First Snow Feast",
   "Harvest of Songs"
  ]
 }
};
})(typeof window !== "undefined" ? window : globalThis);
