/* data-events.js - the REQUIRED canonical events (verbatim from spec), each
 * anchored to a named landmark. Prehistory + extra events generated by the
 * content workflow are merged in (see data-events-extra.js, loaded after). */
(function (root) {
  'use strict';
  var App = root.App || (root.App = {});
  var AT = App.geo.at;

  // [year, id, name, type, landmark, civ, desc, exploreRoute?]
  var raw = [
    [-40000, 'out_of_africa', 'Out of Africa', 'DISCOVERY', 'africa_east', 'homo_sapiens', 'Modern humans migrate out of Africa across the globe.'],
    [-12000, 'ice_age_end', 'End of the Ice Age', 'DISASTER', 'doggerland', null, 'Glaciers retreat; seas rise and drown coastal plains.'],
    [-10000, 'agriculture', 'Agricultural Revolution', 'DISCOVERY', 'fertilecrescent', null, 'Farming begins in the Fertile Crescent; villages take root.'],
    [-3200, 'writing', 'Writing Invented', 'DISCOVERY', 'sumer', 'sumer', 'Cuneiform script emerges in Sumer.'],
    [-3100, 'egypt_unified', 'Egypt Unified', 'FOUNDING', 'memphis', 'egypt', 'Menes unites Upper and Lower Egypt under one crown.'],
    [-2560, 'great_pyramid', 'Great Pyramid Built', 'CULTURAL', 'memphis', 'egypt', 'The Great Pyramid of Giza rises for Pharaoh Khufu.'],
    [-1274, 'kadesh', 'Battle of Kadesh', 'WAR', 'kadesh', 'egypt', 'Egypt and the Hittites clash in historys first recorded great battle.'],
    [-776, 'olympics', 'First Olympic Games', 'CULTURAL', 'olympia', 'greece', 'The first Olympiad is held in honor of Zeus.'],
    [-563, 'buddha', 'Birth of Buddha', 'CULTURAL', 'bodhgaya', null, 'Siddhartha Gautama is born; Buddhism will follow.'],
    [-551, 'confucius', 'Birth of Confucius', 'CULTURAL', 'qufu', 'shang_zhou', 'Confucius is born; his teachings will shape East Asia.'],
    [-490, 'marathon', 'Battle of Marathon', 'WAR', 'marathon', 'greece', 'Athens defeats the Persian invasion on the plain of Marathon.'],
    [-431, 'peloponnesian', 'Peloponnesian War', 'WAR', 'athens', 'greece', 'Athens and Sparta begin a generation of ruinous war.'],
    [-323, 'alexander_dies', 'Death of Alexander', 'COLLAPSE', 'babylon', 'alexander', 'Alexander dies at 32; his empire is torn apart by his generals.'],
    [-221, 'great_wall', 'Great Wall Begun', 'CULTURAL', 'beijing', 'qin', 'Qin Shi Huang links the northern walls into one Great Wall.'],
    [-44, 'caesar', 'Caesar Assassinated', 'WAR', 'rome', 'rome_republic', 'Julius Caesar is stabbed by senators on the Ides of March.'],
    [-4, 'jesus', 'Birth of Jesus', 'CULTURAL', 'judea', null, 'Jesus of Nazareth is born in Roman Judea.'],
    [79, 'vesuvius', 'Vesuvius Erupts', 'DISASTER', 'vesuvius', 'rome_empire', 'Mount Vesuvius buries Pompeii and Herculaneum in ash.'],
    [105, 'paper', 'Paper Invented', 'DISCOVERY', 'luoyang', 'han', 'Cai Lun perfects papermaking at the Han court.'],
    [476, 'fall_rome', 'Fall of Western Rome', 'COLLAPSE', 'rome', 'rome_empire', 'The last Western emperor is deposed; antiquity ends in the west.'],
    [570, 'muhammad', 'Birth of Muhammad', 'CULTURAL', 'mecca', null, 'The Prophet Muhammad is born in Mecca.'],
    [793, 'viking_raids', 'Viking Raids Begin', 'WAR', 'london', 'viking', 'Norsemen sack Lindisfarne; the Viking Age erupts.'],
    [1066, 'hastings', 'Battle of Hastings', 'WAR', 'hastings', null, 'William the Conqueror seizes England for the Normans.'],
    [1095, 'crusade', 'First Crusade', 'WAR', 'jerusalem', null, 'Western knights march east to take the Holy Land.'],
    [1206, 'genghis', 'Genghis Khan Unites Mongols', 'FOUNDING', 'karakorum', 'mongol', 'Temujin is proclaimed Genghis Khan, ruler of all the Mongols.'],
    [1215, 'magna_carta', 'Magna Carta Signed', 'CULTURAL', 'london', null, 'English barons force King John to limit the crowns power.'],
    [1347, 'black_death', 'Black Death', 'DISASTER', 'venice', null, 'Plague reaches Europe and kills a third of its people.'],
    [1453, 'fall_constantinople', 'Fall of Constantinople', 'COLLAPSE', 'constantinople', 'byzantine', 'Ottoman cannon breach the walls; the Byzantine Empire ends.'],
    [1405, 'zhenghe', "Zheng He's Treasure Fleet", 'TRADE', 'nanjing', 'ming_qing', 'Ming China launches vast voyages across the Indian Ocean.', 'zhenghe'],
    [1492, 'columbus', 'Columbus Reaches America', 'DISCOVERY', 'hispaniola', 'spain_empire', 'Columbus makes landfall in the Caribbean for Spain.', 'columbus'],
    [1498, 'dagama', 'da Gama Reaches India', 'TRADE', 'calicut', 'portugal_empire', 'Vasco da Gama opens the sea route from Europe to India.', 'dagama'],
    [1522, 'magellan', 'First Circumnavigation', 'DISCOVERY', 'magellanstrait', 'spain_empire', "Magellan's expedition completes the first voyage around the world.", 'magellan'],
    [1517, 'reformation', 'Protestant Reformation', 'CULTURAL', 'wittenberg', null, 'Luther nails his 95 Theses; Christendom splits.'],
    [1543, 'copernicus', 'Copernican Model', 'SCIENTIFIC', 'vienna', null, 'Copernicus places the Sun, not Earth, at the center.'],
    [1588, 'armada', 'Spanish Armada Defeated', 'WAR', 'london', 'spain_empire', 'Storms and English fireships scatter the great Armada.'],
    [1687, 'newton', "Newton's Principia", 'SCIENTIFIC', 'london', null, 'Newton publishes the laws of motion and gravitation.'],
    [1776, 'us_independence', 'US Independence', 'FOUNDING', 'boston', 'usa', 'Thirteen colonies declare independence from Britain.'],
    [1789, 'french_rev', 'French Revolution', 'WAR', 'paris', null, 'The Bastille falls; liberty, equality, fraternity.'],
    [1804, 'napoleon', 'Napoleon Crowned', 'FOUNDING', 'paris', 'france_napoleon', 'Napoleon crowns himself Emperor of the French.'],
    [1815, 'waterloo', 'Battle of Waterloo', 'WAR', 'waterloo', 'france_napoleon', 'Wellington and Blucher end Napoleons reign at Waterloo.'],
    [1848, 'revolutions', 'Year of Revolutions', 'WAR', 'vienna', null, 'Revolt sweeps across the capitals of Europe.'],
    [1861, 'us_civil_war', 'US Civil War', 'WAR', 'gettysburg', 'usa', 'North and South go to war over union and slavery.'],
    [1869, 'suez', 'Suez Canal Opens', 'TRADE', 'suez', null, 'A canal joins the Mediterranean and Red Sea.'],
    [1879, 'lightbulb', 'Edison Lightbulb', 'SCIENTIFIC', 'nyc', 'usa', 'Edison demonstrates a practical incandescent lamp.'],
    [1903, 'wright', 'Wright Brothers Fly', 'SCIENTIFIC', 'kittyhawk', 'usa', 'The first powered, controlled flight at Kitty Hawk.'],
    [1914, 'wwi', 'World War I Begins', 'WAR', 'sarajevo', null, 'An assassination in Sarajevo ignites the Great War.'],
    [1917, 'russian_rev', 'Russian Revolution', 'WAR', 'stpetersburg', 'russia_empire', 'The Bolsheviks overthrow the Tsar and seize power.'],
    [1929, 'depression', 'Great Depression', 'COLLAPSE', 'nyc', 'usa', 'Wall Street crashes; the world economy collapses.'],
    [1939, 'wwii', 'World War II Begins', 'WAR', 'berlin', 'germany', 'Germany invades Poland; the world goes to war again.'],
    [1945, 'atomic', 'Atomic Bombs Dropped', 'WAR', 'hiroshima', 'japan_empire', 'Hiroshima and Nagasaki end the war in a flash.'],
    [1947, 'india_indep', 'Indian Independence', 'FOUNDING', 'delhi', 'india_modern', 'India wins freedom from the British Empire.'],
    [1957, 'sputnik', 'Sputnik Launched', 'SCIENTIFIC', 'baikonur', 'ussr', 'The Soviets launch the first satellite; the space age begins.'],
    [1969, 'moon', 'Moon Landing', 'SCIENTIFIC', 'capecanaveral', 'usa', 'Apollo 11 lands; humans walk on the Moon.'],
    [1989, 'berlin_wall', 'Berlin Wall Falls', 'COLLAPSE', 'berlinwall', null, 'The Wall comes down; the Cold War thaws.'],
    [1991, 'ussr_end', 'Soviet Union Dissolves', 'COLLAPSE', 'moscow', 'ussr', 'The USSR breaks apart into fifteen nations.'],
    [2001, 'sept11', 'September 11 Attacks', 'WAR', 'nyc', 'usa', 'Hijacked planes destroy the Twin Towers.'],
    [2008, 'financial_crisis', 'Global Financial Crisis', 'COLLAPSE', 'nyc', null, 'A banking collapse triggers a worldwide recession.'],
    [2020, 'covid', 'COVID-19 Pandemic', 'DISASTER', 'wuhan', null, 'A novel coronavirus spreads across the planet.']
  ];

  function build(rows) {
    return rows.map(function (r) {
      var loc = AT(r[4]) || [50, 50];
      return {
        year: r[0], id: r[1], name: r[2], type: r[3], landmark: r[4],
        location: loc, civ: r[5] || null, description: r[6] || '',
        explore: r[7] || null, canonical: true
      };
    });
  }

  App.data = App.data || {};
  App.data.events = build(raw);
  App.data._buildEvent = build; // reused by extra/prehistory loader

  if (typeof module !== 'undefined' && module.exports) { module.exports = { events: App.data.events, build: build }; }
})(typeof window !== 'undefined' ? window : globalThis);
